# Generated by Django 4.0.6 on 2022-09-16 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todos',
            old_name='taskname',
            new_name='task_name',
        ),
    ]
